session_name: nvim
windows:
- focus: 'true'
  layout: 62cc,231x51,0,0[231x25,0,0,21,231x25,0,26,26]
  options:
    automatic-rename: 'off'
  panes:
  - pane
  - bash
  start_directory: /home/mallain/catkin_ws/src
  window_name: ws
- layout: d921,231x51,0,0,22
  options:
    automatic-rename: 'off'
  panes:
  - pane
  start_directory: /home/mallain
  window_name: ipython
- layout: 980e,231x51,0,0[231x40,0,0,23,231x10,0,41,27]
  options:
    automatic-rename: 'off'
  panes:
  - binfmt-bypass
  - focus: 'true'
    shell_command: bash
  start_directory: /home/mallain/catkin_ws/src
  window_name: edit
- layout: eb8e,231x51,0,0[231x35,0,0,24,231x15,0,36,25]
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command:
    - cd /home/mallain/.dotfiles
    - binfmt-bypass
  - shell_command:
    - cd /home/mallain
    - bash
  window_name: dot
- layout: d927,231x51,0,0,28
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command: bash
  start_directory: /home/mallain
  window_name: test
